export const text = {
  mmpi: "MMPI",
  wechsler: "Wechsler",
  simpStrop: "استروپ ساده",
  wiscCards: "کارت های ویسکانسین",
  goBack: "برو - نرو",
  londonTower: "برج لندن",
  bart: "بارت",
  twistedStrop: "استروپ پیچیده",
  nBack: "NBACK",
  eq: "EQ",
  scl90: "SCL90",
  neo: "NEO",
  brainMapping: "نقشه نگاری مغزی",
};
