export const text = {
  title1: "اکوکاردیوگرافی",
  q1: "تصویر نوار قلب :",
  q2: "تشخیص:",
  q3: "ECG:",
  q4: "اقدامات مراقبتی:",
  q5: "توضیح:",
  q6: "Cardiac final conclusion:",
  q7: "نشان دادن ",
  buttonShow: "نمایش",
  result: "نتیجه گیری :",
  conclusion: "conclusion :",
  normalHeartExamination: "Normal Heart Examination :",
  Diagnosis: "Diagnosis",
  hr: "فایل هولتر ضربان خون",
  cHr: "بررسی فایل هولتر ضربان خون",
  bP: "فایل هولتر فشار خون",
  cBp: "بررسی فایل هولتر فشار خون",
  sH: "فایل تست ورزش",
};
